estudosusp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('staticpages.urls')),
    path('admin/', admin.site.urls),
    path('locais/', include('locais.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

locais/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'locais'
urlpatterns = [
    path('', views.LocalListView.as_view(), name='index'),
    path('<int:pk>/', views.LocalDetailView.as_view(), name='detail'),
    path('create/', views.create_local, name='create'),
    path('update/<int:local_id>/', views.update_local, name='update'),
    path('rate/<int:local_id>/', views.rate_local, name='rate'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('create_list/', views.ListCreateView.as_view(), name='create_list'),
    path('detail_list/<int:list_id>/', views.detail_list, name='detail_list'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import register

urlpatterns = [
    path('register/', register, name='register'),
]

locais/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from enum import IntEnum
from django.db.models import Avg
from django.utils.timezone import datetime

class Local(models.Model):

    class Status(models.TextChoices):
        VAZIO = 'Vazio', _('Vazio')
        MEDIO = 'Médio', _('Médio')
        CHEIO = 'Cheio', _('Cheio')

    class SN(models.TextChoices):
        SIM = 'Sim', _('Sim')
        NAO = 'Não', _('Não')

    class Ruido(models.TextChoices):
        BAIXO = 'Baixo', _('Baixo')
        MEDIO = 'Médio', _('Médio')
        ALTO = 'Alto', _('Alto')

    class Permissoes(models.TextChoices):
        COMIDA = 'Permitido comida e água', _("Permitido comida e água")
        SEMCOMIDA = 'Não é permitida a ingestão de alimentos', _("Não é permitida a ingestão de alimentos")

    class Flexibilidade(models.TextChoices):
        MOCHILA = 'É permitido entrar de mochila', _("É permitido entrar de mochila")
        ARMARIO = 'É preciso guardar os pertences em armários', _("É preciso guardar os pertences em armários")

    class DiasFunc(models.TextChoices):
        SEGSEX = 'Segunda a sexta', _('Segunda a sexta')
        TODODIA = 'Todos os dias', _('Todos os dias')
        SEGSAB = 'Segunda a sábado', _('Segunda a sábado')
        OUTRO = 'Verificar no local', _('Verificar no local')

    nome = models.CharField(max_length=200)
    status = models.CharField(max_length=5, choices=Status.choices, default=Status.VAZIO)
    tomada = models.CharField(max_length=5, choices=SN.choices, default=SN.SIM)
    ruido = models.CharField(max_length=5, choices=Ruido.choices, default=Ruido.BAIXO)
    coberto = models.CharField(max_length=5, choices=SN.choices, default=SN.SIM)
    grupo = models.CharField(max_length=5, choices=SN.choices, default=SN.SIM)
    permissoes = models.CharField(max_length=50, choices=Permissoes.choices, default=Permissoes.COMIDA)
    flexibilidade = models.CharField(max_length=50, choices=Flexibilidade.choices, default=Flexibilidade.MOCHILA)
    imagem = models.ImageField(upload_to='uploads/', default='../media/uploads/study.jpg')
    inicio_func = models.TimeField()
    fim_func = models.TimeField()
    dias_func = models.CharField(max_length=50, choices=DiasFunc.choices, default=DiasFunc.SEGSEX)
    atualizacao = models.DateTimeField(auto_now=True)

    def average_rating(self):
        return Avaliacao.objects.filter(local=self).aggregate(Avg("rating"))["rating__avg"]

    def rating_count(self):
        return Avaliacao.objects.filter(local=self).count()

    def __str__(self):
        return f'{self.nome}'

class Avaliacao(models.Model):

    class TiposAval(IntEnum):
        PESSIMO = 1
        RUIM = 2
        MEDIO = 3
        BOM = 4
        OTIMO = 5

        @classmethod
        def choices(cls):
          return [(key.value, key.name) for key in cls]

    local = models.ForeignKey(Local, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=TiposAval.choices(), default=TiposAval.MEDIO)

    def __str__(self):
        return f"{self.local.nome}: {self.rating}"

class LocalList(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=400)
    local = models.ManyToManyField(Local)

    def __str__(self):
        return f'{self.title} por {self.author}'

locais/forms.py
from django.forms import ModelForm
from .models import Local, Avaliacao, LocalList

class LocalForm(ModelForm):
    class Meta:
        model = Local
        fields = [
            'nome',
            'status',
            'tomada',
            'ruido',
            'coberto',
            'grupo',
            'permissoes',
            'flexibilidade',
            'imagem',
            'inicio_func',
            'fim_func',
            'dias_func',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Data de Lançamento',
            'poster_url': 'URL do Poster',
            'nome': 'Nome do Local',
            'status': 'Status do Local',
            'tomada': 'Tomadas Disponíveis',
            'ruido' : 'Nivel de Ruído',
            'coberto': 'Local Coberto',
            'grupo': 'Estudo em Grupo',
            'permissoes': 'Permissões',
            'flexibilidade': 'Flexibilidade',
            'imagem' : 'Imagem do Local',
            'inicio_func': 'Início do funcionamento',
            'fim_func': "Fim do funcionamento",
            'dias_func': 'Dias de funcionamento',
        }

class RateForm(ModelForm):
    class Meta:
        model = Avaliacao
        fields = [
            'rating',
        ]
        labels = {
            'rating': 'Avaliação',
        }

locais/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Local
from django.views import generic
from django.urls import reverse, reverse_lazy
from .models import Local, Avaliacao, LocalList
from .forms import LocalForm, RateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class LocalListView(generic.ListView):
    local = Local
    template_name = 'locais/index.html'

    def get_queryset(self):
        return Local.objects.order_by('id')

class LocalDetailView(generic.DetailView):
    local = Local
    template_name = 'locais/detail.html'

    def get_queryset(self):
        return Local.objects.all()

@login_required
def create_local(request):
    local = Local()

    if request.method == "POST":
        form = LocalForm(request.POST, request.FILES)
        if form.is_valid():
            local.nome = form.cleaned_data['nome']
            local.status = form.cleaned_data['status']
            local.tomada = form.cleaned_data['tomada']
            local.ruido = form.cleaned_data['ruido']
            local.coberto = form.cleaned_data['coberto']
            local.grupo = form.cleaned_data['grupo']
            local.permissoes = form.cleaned_data['permissoes']
            local.flexibilidade = form.cleaned_data['flexibilidade']
            local.imagem = form.cleaned_data['imagem']
            local.inicio_func = form.cleaned_data['inicio_func']
            local.fim_func = form.cleaned_data['fim_func']
            local.dias_func = form.cleaned_data['dias_func']
            local.save()
            return HttpResponseRedirect(
                reverse('locais:detail', args=(local.id, )))
    else:
        form = LocalForm()
    context = {'local': local, 'form': form}
    return render(request, 'locais/create.html', context)

@login_required
def update_local(request, local_id):
    local = get_object_or_404(Local, pk=local_id)

    if request.method == "POST":
        form = LocalForm(request.POST, request.FILES)
        if form.is_valid():
            local.nome = form.cleaned_data['nome']
            local.status = form.cleaned_data['status']
            local.tomada = form.cleaned_data['tomada']
            local.ruido = form.cleaned_data['ruido']
            local.coberto = form.cleaned_data['coberto']
            local.grupo = form.cleaned_data['grupo']
            local.permissoes = form.cleaned_data['permissoes']
            local.flexibilidade = form.cleaned_data['flexibilidade']
            local.imagem = form.cleaned_data['imagem']
            local.inicio_func = form.cleaned_data['inicio_func']
            local.fim_func = form.cleaned_data['fim_func']
            local.dias_func = form.cleaned_data['dias_func']
            local.save()
            return HttpResponseRedirect(
                reverse('locais:detail', args=(local.id, )))
    else:
        form = LocalForm(
            initial={
                'nome': local.nome,
                'status': local.status,
                'tomada': local.tomada,
                'ruido': local.ruido,
                'coberto': local.coberto,
                'grupo': local.grupo,
                'permissoes': local.permissoes,
                'flexibilidade': local.flexibilidade,
                'imagem': local.imagem,
                'inicio_func': local.inicio_func,
                'fim_func': local.fim_func,
                'dias_func': local.dias_func,
            })

    context = {'local': local, 'form': form}
    return render(request, 'locais/update.html', context)

@login_required
def rate_local(request, local_id):
    local = get_object_or_404(Local, pk=local_id)
    if request.method == 'POST':
        form = RateForm(request.POST)
        if form.is_valid():
            avaliacao_local = form.cleaned_data['rating']
            avaliacao = Avaliacao(local=local,
                                rating = avaliacao_local)
            avaliacao.save()
            return HttpResponseRedirect(
                reverse('locais:detail', args=(local_id, )))
    else:
        form = RateForm()
    context = {'form': form, 'local': local}
    return render(request, 'locais/rate.html', context)

class ListListView(generic.ListView):
    model = LocalList
    template_name = 'locais/lists.html'

class ListCreateView(LoginRequiredMixin, generic.CreateView):
    model = LocalList
    template_name = 'locais/create_list.html'
    fields = ['author', 'title', 'description', 'local']
    success_url = reverse_lazy('locais:lists')

def detail_list(request, list_id):
    list = get_object_or_404(LocalList, pk=list_id)
    context = {'list': list}
    return render(request, 'locais/detail_list.html', context)

locais/templates/locais/addlocal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar novo local</title>
    <link rel="stylesheet" href="addlocalstyle.css">
</head>
<body>
    <h1>ESTUDOS USP</h1>
    <div class="topnav">
        <a class="activate" href="#paginainicial">Página Inicial</a>
        <a href="#adicionarnovolocal">Adicionar novo local</a>
        <a href="#usuario">Usuário</a>
    </div>
    <form>
        <label for="anexafoto">Anexar foto</label>
        <label for="nomelocal">Nome do local:</label>
        </br>
        <textarea></textarea>
        </br>
        <label for="status">Status:</label>
            <select id="status" name="status">
                <option value="vazio">Vazio</option>
                <option value="medio">Médio</option>
                <option value="cheio">Cheio</option>
            </select>
        </br>
        <label for="tomada">Tomada:</label>
            <select id="tomada" name="tomada">
                <option value="sim">Sim</option>
                <option value="nao">Não</option>
            </select>
        </br>
        <label for="ruido">Ruído:</label>
            <select id="ruido" name="ruido">
                <option value="vazio">Baixo</option>
                <option value="medio">Médio</option>
                <option value="cheio">Alto</option>
            </select>
        </br>
        <label for="coberto">Coberto:</label>
            <select id="coberto" name="coberto">
                <option value="sim">Sim</option>
                <option value="nao">Não</option>
            </select>
        </br>
        <label for="emgrupo">Em grupo:</label>
            <select id="emgrupo" name="emgrupo">
                <option value="sim">Sim</option>
                <option value="nao">Não</option>
            </select>
        </br>
        <label for="permissoes">Permissões:</label>
            <select id="permissoes" name="permissoes">
                <option value="sim">É permitida e ingestão de alimentos</option>
                <option value="nao">Não é permitida e ingestão de alimentos</option>
            </select>
        </br>
        <label for="flexacesso">Flexibilidade de Acesso:</label>
            <select id="flexacesso" name="flexacesso">
                <option value="sim">É preciso guardar seus pertences em armários</option>
                <option value="nao">Não é preciso guardar seus pertences em armários</option>
            </select>
        </br>
        <label for=""></label>
        <label for="horariofuncionamento">Horário de Funcionamento:</label>
            <select id="horariofuncionamento" name="horariofuncionamento">
                <option value="00h">00h</option>
                <option value="01h">01h</option>
                <option value="02h">02h</option>
                <option value="03h">03h</option>
                <option value="04h">04h</option>
                <option value="05h">05h</option>
                <option value="06h">06h</option>
                <option value="07h">07h</option>
                <option value="08h">08h</option>
                <option value="09h">09h</option>
                <option value="10h">10h</option>
                <option value="11h">11h</option>
                <option value="12h">12h</option>
                <option value="13h">13h</option>
                <option value="14h">14h</option>
                <option value="15h">15h</option>
                <option value="16h">16h</option>
                <option value="17h">17h</option>
                <option value="18h">18h</option>
                <option value="19h">19h</option>
                <option value="20h">20h</option>
                <option value="21h">21h</option>
                <option value="22h">22h</option>
                <option value="23h">23h</option>
            </select>
            <text>às</text>
            <select id="horariofuncionamento" name="horariofuncionamento">
                <option value="00h">00h</option>
                <option value="01h">01h</option>
                <option value="02h">02h</option>
                <option value="03h">03h</option>
                <option value="04h">04h</option>
                <option value="05h">05h</option>
                <option value="06h">06h</option>
                <option value="07h">07h</option>
                <option value="08h">08h</option>
                <option value="09h">09h</option>
                <option value="10h">10h</option>
                <option value="11h">11h</option>
                <option value="12h">12h</option>
                <option value="13h">13h</option>
                <option value="14h">14h</option>
                <option value="15h">15h</option>
                <option value="16h">16h</option>
                <option value="17h">17h</option>
                <option value="18h">18h</option>
                <option value="19h">19h</option>
                <option value="20h">20h</option>
                <option value="21h">21h</option>
                <option value="22h">22h</option>
                <option value="23h">23h</option>
            </select>
        </br>
        <label for="avaliacao">Avaliação:</label>
            <select id="avaliacao" name="avaliacao">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
            </select>
        </br>
        <button id="cancelar">Cancelar</button>
        <button id="voltar">Voltar</button>
        <button id="ok">OK</button>
    </form>
</body>
</html>

locais/templates/locais/create.html
{% extends 'base.html' %}

{% block content %}
<div class="register-card">
    <div class="register-card-title"><h2>Adicionar novo local</h2></div>
    
    <form method="POST" enctype="multipart/form-data" action="{% url 'locais:create'%}" id="register-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Adicionar</button>
    </form>
    <p><a href="{% url 'locais:index' %}" >Voltar</a> </p>
</div>

{% endblock content %}

locais/templates/locais/create_list.html
{% extends 'base.html' %}

{% block content %}
<div class="register-card">
    <div class="register-card-title"><h2>Criar nova lista</h2></div>
    
    <form method="POST" action="{% url 'locais:create_list'%}" id="register-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar</button>
    </form>
    <p><a href="{% url 'locais:index' %}" >Voltar</a> </p>
</div>

{% endblock content %}

locais/templates/locais/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
    <section class="detail">
        <h1> {{ local.nome }} </h1>
        <p><i>Última atualização em {{local.atualizacao}}</i></p>
        <div class="detail-local">
            <div class="detail-items">
                <img src="..{{local.imagem.url}}" alt="{{local.nome}}" width="60%" height="auto">
                <div class="detail-info">
                    <p> <b>Status:</b> {{ local.status }}</p>
                    <p> <b>Possui tomada?</b> {{ local.tomada }} </p>
                    <p> <b>Ruído:</b> {{ local.ruido }}</p>
                    <p> <b>É coberto?</b> {{ local.coberto }}</p>
                    <p> <b>É possível estudar em grupo?</b> {{ local.grupo }}</p>
                    <p> <b>Permissões:</b> {{ local.permissoes }}</p>
                    <p> <b>Flexibilidade:</b> {{ local.flexibilidade }}</p>
                    <p> <b>Funcionamento:</b> </p>
                    <p>{{local.dias_func}} das {{ local.inicio_func }} às {{local.fim_func}}</p>
    
                    {% if local.avaliacao_set.all %}
                        <p>Nota média: {{ local.average_rating }} / 5,0 </p>
                        <p>Número de avaliações: {{ local.rating_count }} </p>
                    {% else %}
                        <p><i>Não há avaliações para este local.</i></p>
                    {% endif %}
                </div>
            </div>
            <div class="detail-edicao">
                <p><a href="{% url 'locais:update' local.id %}" >Atualizar dados deste local</a> </p>
                <p><a href="{% url 'locais:rate' local.id %}" >Avaliar local</a> </p>
                <p><a href="{% url 'locais:index' %}" >Voltar</a> </p>
            </div>
        </div>
        
    </section>
    
</body>
{% endblock content %}

locais/templates/locais/detail_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
    <section class="detail">
        <h1> {{ list.title }} </h1>
        <div class="detail-local">
            <div class="detail-items">
                <div class="detail-info">
                    <p><i> {{list.description}}</i></p>
                    <p>Locais incluídos nessa lista:</p>
                    {% for local in list.local.all %}
                    <a class='link-local' href="{% url 'locais:detail' local.id %}"> {{local.nome}} </a>
                    {% endfor %}
                </div>
            </div>
            <div class="detail-edicao">
                <p><a href="{% url 'locais:lists' %}" >Voltar</a> </p>
            </div>
        </div>
        
    </section>
    
</body>
{% endblock content %}

locais/templates/locais/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
    <section>
        <h1><i>Locais de Estudo dentro da USP</i></h1>
        <p>Abaixo estão os locais para estudar na USP! Se você não encontrou algum local,
            você pode adicionar um novo!
        </p>

            {% if local_list %}
            {% for local in local_list %}

            
            <div class="local-item">
                <img src="{{local.imagem.url}}" alt="{{local.nome}}" width="240px" heigh="180px">
                <div class="local-item-descricao">
                    <h3>{{ local.nome }} </h3>
                    <p>Status: {{ local.status }}</p>
                    <p>Última atualização: {{ local.atualizacao }}</p>
                </div>
                <a href="{% url 'locais:detail' local.id %}">Saiba mais!</a>
            </div>
            {% endfor %}
            {% else %}
            <p>Não foi encontrado nenhum local.</p>
            {% endif %}
            <a href="{% url 'locais:lists' %}">Ver listas de locais</a>
            <a href="{% url 'locais:create_list' %}">Criar uma lista de locais</a>
            </div>

    </section>

</body>
{% endblock content %}

locais/templates/locais/lists.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
    <section>
        <h1><i>Listas de locais</i></h1>
        <p>Os usuários podem criar listas de locais de estudo com os critérios que quiserem. 
            Aqui você pode ver as listas criadas até agora! 
        </p>

            {% for list in locallist_list %}

            <div class="local-item">
                <div class="local-item-descricao">
                    <h3>{{ list.title }} </h3>
                    <p> {{ list.description }}</p>
                    <p> Lista feita por: {{ list.author }}</p>
                </div>
                <p><a href="{% url 'locais:detail_list' list.id %}">Saiba mais!</a></p>
            </div>
            {% endfor %}
            </div>

    </section>

</body>
{% endblock content %}

locais/templates/locais/rate.html
{% extends 'base.html' %}

{% block content %}

<div class="register-card">
    <div class="register-card-title"><h2>Avaliar {{ local.name }}</h2></div>

    <form method="POST" action="{% url 'locais:rate' local.id%}" id="register-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Avaliar</button>
        <p><a href="{% url 'locais:detail' local.id %}" >Voltar</a> </p>
    </form>
</div>

{% endblock content %}

locais/templates/locais/update.html
{% extends 'base.html' %}

{% block content %}
<div class="register-card">
    <div class="register-card-title"><h2>Atualizar Dados do Local {{ local.name }}</h2></div>
    
    <form method="POST" enctype="multipart/form-data" action="{% url 'locais:update' local.id%}" id="register-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Atualizar</button>
    </form>
</div>

{% endblock content %}